# Generated by Django 5.0.8 on 2024-10-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fechaInicio', models.DateField()),
                ('fechaTermino', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('prioridad', models.IntegerField()),
            ],
        ),
    ]
